export const FETCH_RATES_RESPONSE = "EXCHANGE/FETCH_RATES_RESPONSE";
export const CHANGE_FROM_CURRENCY = "EXCHANGE/CHANGE_FROM_CURRENCY";
export const CHANGE_FROM_AMOUNT = "EXCHANGE/CHANGE_FROM_AMOUNT";
export const CHANGE_TO_CURRENCY = "EXCHANGE/CHANGE_TO_CURRENCY";
export const EXCHANGE_RESPONSE = "EXCHANGE/EXCHANGE_RESPONSE";
export const RESET_DATA = "EXCHANGE/RESET_DATA";